STATE_TAX_RATES = {
    # No state income tax
    "AK": 0.00,
    "FL": 0.00,
    "NV": 0.00,
    "SD": 0.00,
    "TN": 0.00,
    "TX": 0.00,
    "WA": 0.00,
    "WY": 0.00,

    # Low flat / effective rates
    "AZ": 0.025,
    "CO": 0.045,
    "GA": 0.045,
    "ID": 0.058,
    "IN": 0.032,
    "KY": 0.045,
    "MI": 0.0425,
    "NC": 0.045,
    "PA": 0.0307,
    "UT": 0.0485,

    # Moderate
    "AL": 0.050,
    "AR": 0.055,
    "IA": 0.055,
    "KS": 0.057,
    "LA": 0.050,
    "MO": 0.050,
    "MS": 0.050,
    "NE": 0.055,
    "NM": 0.049,
    "ND": 0.0425,
    "OK": 0.050,
    "SC": 0.060,
    "VT": 0.060,
    "WV": 0.060,
    "WI": 0.060,

    # Higher-tax states
    "CA": 0.070,
    "CT": 0.060,
    "DE": 0.055,
    "HI": 0.070,
    "IL": 0.0495,
    "ME": 0.065,
    "MD": 0.057,
    "MA": 0.050,
    "MN": 0.070,
    "MT": 0.060,
    "NJ": 0.065,
    "NY": 0.070,
    "OH": 0.035,
    "OR": 0.080,
    "RI": 0.060,
    "VA": 0.050
}


DISCLAIMER = "Estimates only. Not tax advice."

# Maintain display names alongside rate lookup to keep API/UI in sync.
STATE_DISPLAY_NAMES = {
    "AK": "Alaska",
    "AL": "Alabama",
    "AR": "Arkansas",
    "AZ": "Arizona",
    "CA": "California",
    "CO": "Colorado",
    "CT": "Connecticut",
    "DE": "Delaware",
    "FL": "Florida",
    "GA": "Georgia",
    "HI": "Hawaii",
    "IA": "Iowa",
    "ID": "Idaho",
    "IL": "Illinois",
    "IN": "Indiana",
    "KS": "Kansas",
    "KY": "Kentucky",
    "LA": "Louisiana",
    "MA": "Massachusetts",
    "MD": "Maryland",
    "ME": "Maine",
    "MI": "Michigan",
    "MN": "Minnesota",
    "MO": "Missouri",
    "MS": "Mississippi",
    "MT": "Montana",
    "NC": "North Carolina",
    "ND": "North Dakota",
    "NE": "Nebraska",
    "NJ": "New Jersey",
    "NM": "New Mexico",
    "NV": "Nevada",
    "NY": "New York",
    "OH": "Ohio",
    "OK": "Oklahoma",
    "OR": "Oregon",
    "PA": "Pennsylvania",
    "RI": "Rhode Island",
    "SC": "South Carolina",
    "SD": "South Dakota",
    "TN": "Tennessee",
    "TX": "Texas",
    "UT": "Utah",
    "VA": "Virginia",
    "VT": "Vermont",
    "WA": "Washington",
    "WI": "Wisconsin",
    "WV": "West Virginia",
    "WY": "Wyoming",
}
